# Generated by Django 2.2.1 on 2020-02-03 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('Classroom_id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('School_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=32)),
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='id',
        ),
        migrations.AddField(
            model_name='child',
            name='child_id',
            field=models.AutoField(default='null', primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='Classroom_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Data.Classroom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='School_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Data.School'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='Teacher_id',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.CASCADE, to='Data.Teacher'),
            preserve_default=False,
        ),
    ]
